# Generated by Django 5.1.1 on 2024-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
